name       : haskell-unix-time
version    : 0.3.7
release    : 1
source     :
    - http://hackage.haskell.org/package/unix-time-0.3.7/unix-time-0.3.7.tar.gz : 1131301131dd3e73353a346daa04578ec067073e7674d447051ac1a87262b4e1
license    : BSD-3-Clause
component  : programming.haskell
summary    : Fast parser/formatter/utilities for Unix time
description: |
    Fast parser/formatter/utilities for Unix time
builddeps  :
    - haskell-cabal-install
    - haskell-old-time
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register

    