name       : haskell-unix-time
version    : 0.3.8
release    : 4
source     :
    - https://hackage.haskell.org/package/unix-time-0.3.8/unix-time-0.3.8.tar.gz : dca1bd332f4690f667570868c91c1270083428067e0e20b88a9d9516efa33a14
license    : BSD-3-Clause
component  : programming.haskell
summary    : Fast parser/formatter/utilities for Unix time
description: |
    Fast parser/formatter/utilities for Unix time
builddeps  :
    - ghc
    - haskell-cabal-install
    - haskell-old-time
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
