name       : haskell-unix-time
version    : 0.4.7
release    : 5
source     :
    - https://hackage.haskell.org/package/unix-time-0.4.7/unix-time-0.4.7.tar.gz : 19233f8badf921d444c6165689253d877cfed58ce08f28cad312558a9280de09
license    : BSD-3-Clause
component  : programming.haskell
summary    : Fast parser/formatter/utilities for Unix time
description: |
    Fast parser/formatter/utilities for Unix time
builddeps  :
    - haskell-cabal-install
    - haskell-old-time-devel
rundeps    :
    - devel:
        - haskell-old-time-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
